version: '3.8'
services:
  #wordpress
  wordpress:
    container_name: spin8_wordpress
    image: talpx1/spin8_wordpress:${WORDPRESS_VERSION:-6.4.2}-php${PHP_VERSION:-8.3}-${WEBSERVER_VERSION:-apache}
    environment:
      - WORDPRESS_DB_HOST=${DATABASE_HOST:-spin8_mariadb}
      - WORDPRESS_DB_USER=${DATABASE_USER:-spin8}
      - WORDPRESS_DB_NAME=${DATABASE_NAME:-wp_spin8}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-spin8}
      - WORDPRESS_TABLE_PREFIX=${DATABASE_TABLE_PREFIX:-wp_}
      - WORDPRESS_LOCALE=${WORDPRESS_LOCALE:-en_US}
      - WORDPRESS_WEBSITE_TITLE=${WORDPRESS_WEBSITE_TITLE:-Spin8 Test}
      - WORDPRESS_WEBSITE_URL=${WORDPRESS_WEBSITE_URL:-http://localhost}
      - WORDPRESS_WEBSITE_URL_WITHOUT_HTTP=${WORDPRESS_WEBSITE_URL_WITHOUT_HTTP:-localhost}
      - WORDPRESS_WEBSITE_POST_URL_STRUCTURE=${WORDPRESS_WEBSITE_POST_URL_STRUCTURE:-/%postname%/}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER:-spin8}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD:-spin8}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:-test@spin8.test}
      - PLUGIN_NAME=${PLUGIN_NAME:-Spin8 Dev}
      - PLUGIN_SLUG=${PLUGIN_SLUG:-spin8-dev}
      - PLUGIN_NAMESPACE=${PLUGIN_NAMESPACE:-Spin8Dev}
      - PLUGIN_FOLDER=${PLUGIN_FOLDER:-${PLUGIN_SLUG}}
      - PLUGIN_ABS_PATH=${PLUGIN_ABS_PATH:-/var/www/html/wp-content/plugins/${PLUGIN_FOLDER}}
    ports:
      - ${WEBSERVER_PORT:-80}:80
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
      - .:${PLUGIN_ABS_PATH}
      - ${SSH_PATH}/${SSH_KEY_NAME}.pub:/root/.ssh/${SSH_KEY_NAME}.pub
      - ${SSH_PATH}/${SSH_KEY_NAME}:/root/.ssh/${SSH_KEY_NAME}
  #mariadb
  mariadb:
    container_name: spin8_mariadb
    image: mariadb:${MARIADB_VERSION:-latest}
    ports:
      - ${DATABASE_PORT:-3306}:3306
    restart: always
    environment:
      - MARIADB_DATABASE=${DATABASE_NAME:-wp_spin8}
      - MARIADB_USER=${DATABASE_USER:-spin8}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD:-spin8}
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=''
      - MARIADB_ROOT_HOST=localhost
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  wp_data:
