#!/usr/bin/env bash

#OS Check
if [[ "$OSTYPE" != "linux-gnu"* ]] || [[ "$OSTYPE" != "darwin"* ]]; then
    echo "Unsupported OS ($OSTYPE)."
    echo "You won't be able to use spin8 install/build/up/down/recreate."
    echo
    echo "!!! If you are on windows, install and run Spin8 inside WSL2 to use all the features !!!"
    echo
    echo "You can still run Spin8 manually with these steps:" 
    echo "1. copy the .env.example file and rename the coiped file .env" 
    echo "2. customize the settings in the .env file" 
    echo "3. start the containers using 'docker compose up -d'" 
    echo "4. install and configure wordpress using 'docker exec spin8_wordpress spin8_install_wp'" 
    echo "5. use any other Spin8 command via './vendor/bin/spin8 command'" 
fi